### PR TITLE
SBANK-86 feat: Add security and jwt configs

### PR DESCRIPTION
**Pull request by szahedi-smoothstack**
These are the 4 files for security config and generating and checking jwt tokens

### CODE REVIEW

**Comment by Parker-Williams-Smoothstack** [comment]
Looked it over and it seems fine to me. There looks to be an extra .and() on line 46 of the SecurityConfig but I don't think it actually makes a difference so other than that I think it's all good.

**Comment by ghost** [comment]
Adding the and() changes the return type back to SecurityBuilder for further configuration, otherwise it would remain a SessionManagementConfigurer.

**Comment by Hemanth-Swarna** [comment]
From what I saw it looks fine Saif.

**Review by Hemanth-Swarna — COMMENTED** [review]
It looks fine.

**Pull request merged**
